apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: db-metrics-servicemonitor
  labels:
    release: prometheus
    team: dev
spec:
  selector:
    matchLabels:
      operated-prometheus: "true"
  endpoints:
  - interval: 15s
    targetPort: prom
